# Generated by Django 3.2.3 on 2021-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scotus_app", "0002_case_docket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_number",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="term_year",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
