# Generated by Django 3.2.3 on 2021-05-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scotus_app', '0005_auto_20210515_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='need_to_send_intial_email',
            new_name='need_to_send_initial_email',
        ),
    ]
