# Generated by Django 3.2.3 on 2021-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotus_app', '0006_rename_need_to_send_intial_email_case_need_to_send_initial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='question_presented',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
